import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from "next/image"
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"

export default function Home() {
  return (
    <>
      <Head>
        <title>James Xalis Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10'>
        <section className='min-h-screen '>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>James Xalis</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className='bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' 
                href="#"
                >
                Resume
                </a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>James Xalis</h2>
            <h3 className=' text-2xl py-2'>Developer and desinger.</h3>
            <p className=' text-md py-5 leading-8 text-gray-800'>
              Freelancer providing services for programing and web design needs. Join me down below and lets get coding!
            </p>
            </div>
            <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <AiFillTwitterCircle/>
              <AiFillLinkedin/>
              <AiFillYoutube/>
          </div>
          <div className='realative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className=' text-md py-2 leading-8 text-gray-80'>
              Since the begining of my journey as a freelance designer and developer, ive done remote work for <span className='text-teal-500'> agencies </span> consulted for <span className='text-teal-500'> startups </span> and collaborated with talented poeople to create digital products for both busines and consumer use. 
            </p>
            <p className=' text-md py-2 leading-8 text-gray-80'>
              I offer a wide range of services, including web desigin, programing, and teaching. 
            </p>
          </div>
          <div>
            <div>
              <Image src={design} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Desings</h3>
              <p className='py-2'>
                Creating elegant designs sutied for you needs follwoing core design thory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>


      </main>
    </>
  );
}
