import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai'
import Image from "next/image"
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import cardBattleGif from '../public/Card-Battle-gif.gif'
import reelSearchGif from '../public/reel-search.gif'
import { useState } from 'react'



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>James Xalis Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen '>
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>
              Developed by Me
            </h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a className='bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'>
              James Xalis
            </h2>
            <h3 className=' text-2xl py-2 md:text-3xl dark:text-white'>
              Developer and desinger.
            </h3>
            <p className=' text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-lg mx-auto'>
              Freelancer providing services for programing and web design needs. Join me down below and lets get coding!
            </p>
          </div>
          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='realative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} />
          </div>
        </section>

        <section>
          <div className='text-center p-10'>
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Since the begining of my journey as a freelance developer, I've built <span className='text-teal-500'> e-commerce </span> businesses, I've done <span className='text-teal-500'> remote work </span> for agencies, <span className='text-teal-500'> consulted </span> for clients and <span className='text-teal-500'> collaborated </span> with talented poeople to create digital products for both busines and consumer use.
            </p>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              I offer a wide range of services, including web desigin, programing, and consulting.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-200'>
              <Image src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Web Design</h3>
              <p className='py-2'>
                Creating elegant designs sutied for you needs follwoing core design thory.
              </p>
              <h4 className='py-4 text-teal-600'>Design Framworks</h4>
              <p className='text-gray-800 py-1'>React.js</p>
              <p className='text-gray-800 py-1'>Tailwindcss</p>
              <p className='text-gray-800 py-1'>Bootstrap</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-200'>
              <Image src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Programing</h3>
              <p className='py-2'>
                I'm always on the look out for new languages. Here are just the top few that I know. 
              </p>
              <h4 className='py-4 text-teal-600'>Programing Languages</h4>
              <p className='text-gray-800 py-1'>JavaScript/TypeScript</p>
              <p className='text-gray-800 py-1'>Python</p>
              <p className='text-gray-800 py-1'>Java</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-200'>
              <Image src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Consulting</h3>
              <p className='py-2'>
                Consulting from your first website to starting and growing your business.
              </p>
              <h4 className='py-4 text-teal-600'>Business tools I use</h4>
              <p className='text-gray-800 py-1'>Slack</p>
              <p className='text-gray-800 py-1'>Meta Business Suite</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div className=' rounded-xl text-center p-10'>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-gray-200 '>
              Here are a few projects I've worked on recently. 
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={cardBattleGif} className='rounded-lg object-voer' width={'100%'} height={'100%'} responsive='true' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={reelSearchGif} className='rounded-lg object-voer' width={'100%'} height={'100%'} responsive='true' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-voer' width={'100%'} height={'100%'} responsive='true' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-voer' width={'100%'} height={'100%'} responsive='true' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-voer' width={'100%'} height={'100%'} responsive='true' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-voer' width={'100%'} height={'100%'} responsive='true' />
            </div>
            <div className=' rounded-xl '>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-gray-200 '>
              When you're ready,<span className='text-teal-500'> contact me </span> and lets build something together.
            </p>
          </div>
          </div>
        </section>
      </main>
    </div>
  );
}
